#!/bin/bash
docker run -t -i -v `pwd`/data:/data -v `pwd`/output:/buildroot/output `whoami`/buildroot build
if [ -f output/images/rootfs.tar ]; then
  docker import - `whoami`/nodejs < output/images/rootfs.tar
fi
